pipelineJob('hello-world-pipeline-job') {
    description('A minimal Hello World pipeline job generated by Job DSL.')
    
    definition {
        cps {
            script('''
                @Library('shared-lib') _
                pipeline {
                    agent any
                    stages {
                        stage('Hello') {
                            steps {
                                echo 'Hello World!'
                            }
                        }
                    }
                    post {
                        success {
                            sendSlackMessage(status: 'SUCCESS', channel: '#jenkins')
                        }
                        failure {
                             sendSlackMessage(status: 'FAILURE', channel: '#jenkins')
                        }
                    }
                }
            '''.stripIndent())
        }
    }
}