pipelineJob('hello-world-pipeline-job') {
    description('A minimal Hello World pipeline job generated by Job DSL.')
    
    definition {
        cps {
            script('''
                pipeline {
                    agent any
                    stages {
                        stage('Hello') {
                            steps {
                                echo 'Hello World!'
                            }
                        }
                    }
                }
            '''.stripIndent())
        }
    }
}